### PR TITLE
Use the Rmath package since libRmath is gone in 0.5

### PR DESCRIPTION
**Pull request by ararslan**
I also added the 0.5 badge and enabled Coveralls.

### CODE REVIEW

**Comment by ararslan** [comment]
Hey @tkelman, this keeps happening on Linux 0.4, but only on the PR build, not the push build: https://travis-ci.org/JuliaStats/StatsFuns.jl/jobs/144655346#L167. Any idea why that's happening? I assume it's a Travis issue but I have no idea.

**Comment by tkelman** [comment]
yeah that's a travis bug. there's a `git: depth: 999999` or similar setting you can add to the yml. may have to check the exact format there

**Comment by ararslan** [comment]
Nice, looks like Linux 0.4 is working now. Thanks!

**Comment by tkelman** [comment]
Thanks for doing this! These were on my list. There are a few others, but maybe it's better for me to focus on getting the binaries up and running and let others handle this kind of change.

**Comment by ararslan** [comment]
It's my pleasure! I'd be happy to help out with the others on your list if you want to focus on binaries.

**Comment by tkelman** [comment]
Anything where grepping all registered packages shows a mention of `libRmath` -
- [x] StatsFuns.jl, closed by this PR
- [x] Rmath.jl, NA
- [ ] Distributions.jl
- [ ] HypothesisTests.jl
- [ ] Sampling.jl
- [x] CorpusTools.jl (commented out?)

**Comment by ararslan** [comment]
Will do 👍

**Comment by ararslan** [comment]
Most of these will require using the newly tagged version of StatsFuns (ref https://github.com/JuliaLang/METADATA.jl/pull/5612) so I won't be able to make the changes until I can also bump the StatsFuns version.

**Comment by tkelman** [comment]
good to know, will keep an eye on the travis queue to merge that asap

**Comment by ararslan** [comment]
It's ready when you are. 😄

**Pull request merged**
