### PR TITLE
Support for zero σ normals

### PR DESCRIPTION
**Pull request by simonbyrne**
This adds support for normal distributions with zero standard deviation. At the moment, this gives the same values as R. The only one I'm not particularly sure about is what to return for the quantile at 1 (R gives +Inf, there is a reasonable argument I think it should be μ).

### CODE REVIEW

**Comment by ararslan** [comment]
> there is a reasonable argument I think it should be μ

Can you elaborate? I would have thought `Inf` would be the most natural choice.

**Comment by simonbyrne** [comment]
Because if σ is zero, the distribution is a point-mass at μ, and this is how we define quantiles in other cases.

That said, I'm not particularly bothered by it (there are also inconsistencies in how we handle the quantile at 0).

**Comment by ararslan** [comment]
Ah, that does indeed make sense. I'd say go with what your heart tells you.

**Comment by simonbyrne** [comment]
The easiest option is to go with what R does. We can always revisit this later.

**Comment by andreasnoack** [comment]
The code complication reflects well that the distribution at `σ=0` is fundamentally different from when `σ>0`. We discussed this a while ago in the context of the Poisson where the consensus, at that time, was to exclude degenerate continuous distributions. Is hitting `σ=0` a common situation in practice? If it is then I'm okay with the change but the code complication is a bit unfortunate.

**Comment by simonbyrne** [comment]
Yes, I'm seeing it in a case where `σ` underflows. Currently there are ugly hacks, like adding `eps()`, but this should make the code much clearer.

**Comment by andreasnoack** [comment]
Okay. It is better to have the special cases here than in user code.

**Comment by tpapp** [comment]
I have been dealing with a lot of similar cases lately in the context of Bayesian inference for a rather complex structural model in economics. Eg for an MCMC sampler that works on unconstrained ℝⁿ, the a variance (which is >0) would be `exp` of some coordinate in ℝ using standard transformations. Underflow is very easy to get during MCMC adaptation.

I tried to make all corner cases work like this PR, but eventually abandonned this and came to the conclusion that the best solution is to error since there is no clearly good choice. Eg if `σ` is a `ForwardDiff.Dual` or similar, I am not sure that the derivatives will make sense (currently one can AD through most distributions for finite, valid values). The user should check for these things and do the appropriate thing (eg reject the parameters for MCMC). It is best not to catch the error to call attention to this.

(PS: realize this was merged while typing this, sorry for the noise).

**Comment by simonbyrne** [comment]
@tpapp Care to share some examples? Handling of invalid values has been one of the biggest challenges with the "distributions as objects" approach, so I'd be keen to learn more about how problems arise.

**Pull request merged**
